name: experiment
on:
  workflow_dispatch:
jobs:
  test-calculator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6.1.0
      - name: Setup Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Unit Tests
        run: pytest test_calculator.py
      - name: Run Security Scan
        run: bandit -r .
          
